# Site settings
title: Oliver Li
description: 'Business Card Page'
url: 'https://oliverli.dev'
baseurl: ''
profilepic: '/images/profile.jpg'
bkimage: '/images/bk1.jpg'
# google_analytics: UA-XXXXXX-X
font_awesome: '398933c53e.js'

author:
  name: 'Oliver Li'
  email: itsme@oliverli.dev
  # twitter_username: thomzuehlke
  facebook_username: 0liverli
  github_username:  oliverli
  linkedin_username:  o-li
  # meetup_name: Azure-Meetup-Rostock-MV

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
